"""create topic_assignments and sentiment_scores tables

Revision ID: df5280af591b
Revises: ee7fad85c1e2
Create Date: 2026-09-09 13:45:13.472972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df5280af591b'
down_revision: Union[str, Sequence[str], None] = 'ee7fad85c1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('masked_record_id', sa.UUID(), nullable=False),
    sa.Column('polarity', sa.Float(), nullable=False),
    sa.Column('friction_index', sa.Float(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['masked_record_id'], ['masked_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('masked_record_id')
    )
    op.create_table('topic_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('masked_record_id', sa.UUID(), nullable=False),
    sa.Column('focus_area', sa.Enum('ASSISTIVE_TECH', 'ORIENTATION_MOBILITY', 'HEALTHCARE_DIAGNOSIS', 'DAILY_LIVING_DIGITAL', name='focusarea'), nullable=False),
    sa.Column('focus_area_similarity', sa.Float(), nullable=False),
    sa.Column('sub_cluster_id', sa.Integer(), nullable=True),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['masked_record_id'], ['masked_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('masked_record_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_assignments')
    op.drop_table('sentiment_scores')
    # ### end Alembic commands ###
