"""create masked_records table

Revision ID: ee7fad85c1e2
Revises: 8db6c3dbd2c3
Create Date: 2026-09-02 13:45:29.438920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7fad85c1e2'
down_revision: Union[str, Sequence[str], None] = '8db6c3dbd2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masked_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('masked_text', sa.Text(), nullable=False),
    sa.Column('entity_types_found', sa.Text(), nullable=True),
    sa.Column('masked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_record_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('masked_records')
    # ### end Alembic commands ###
